### ISSUE TITLE
Source code?

### ISSUE THREAD

**Issue by rouben** [sin2000/zdownloader#5]
I can see binary file downloads, but no source code. Since this project is licensed under the Apache license, it'd be nice to see the source.

I recommend uploading binary releases to the releases section of the project, rather than to the Git repo.

**Comment by sin2000** [comment]
> I recommend uploading binary releases to the releases section of the project, rather than to the Git repo.

@rouben I already uploading binary releases to the releases section.

> I can see binary file downloads, but no source code. Since this project is licensed under the Apache license, it'd be nice to see the source.

Thanks, but I don't want to share source code at least for now, because:
- I don't want to,
- In zdownloader I am currently using my libraries that have additional functionalities not used in the program. So when I isolate source code needed only by zdownloader then I will think about sharing the source code.

**Comment by rouben** [comment]
Thanks for the explanation. I hope to see the source soon! I think the Apache license doesn't require you to release the source code unlike the GPL, but it would certainly make things easier for contributions, which are basically impossible at the moment. I'm also a bit hesitant to try this software out, since it's a black box, and I really don't want to run it unattended on my Linux box.
